### ISSUE TITLE
Cant download missing components for first lauch of Qbundle

### ISSUE THREAD

**Issue by SteveHeringtonson** [PoC-Consortium/Qbundle#41] opened 2018-03-29 10:06 UTC
Qbundle version 2.0.1

I downloaded the .exe file of qbundle but when I try to download the missing compnents I recieve an error of:
Internet is unreachable or repository offline.

What can I do to fix this issue?
Thanks for the help.
Theres probably a step i overlooked. Sorry for the dumb problem.

**Comment by Quibus-burst** [comment] 2018-03-29 10:09
The first time setupscreen have a confirmed error for downloading Components. It is fixed in one of the commits but still not released.

In the meantime, please download and install Windows Offline (64-bit) from here:
https://www.java.com/en/download/manual.jsp

**Comment by SteveHeringtonson** [comment] 2018-03-29 10:20
By any chance you could give me a rough date as to when it would be released as I want to start burst coin minning. I know there is an online wallet alternative but I personally like software based wallets.

**Comment by Real-Duke** [comment] 2018-03-29 12:20
You can install 1.9 and make Auto update to 2.0.0 and a further -manual update- to 2.0.1 because of https://github.com/PoC-Consortium/Qbundle/issues/35
Works for me this way

**Comment by Quibus-burst** [comment] 2018-03-30 16:57
@SteveHeringtonson as i said you can install java manually to get it resolved.

**Comment by Josygold** [comment] 2018-03-31 02:51
I deinstalled the Java 64 bit version for Win10 and installed it fresh and I still have the issue and can't continue installing. 

The update from 2.0.0 to 2.0.1 also dosen't work for me...

**Comment by Quibus-burst** [comment] 2018-03-31 09:21
After you installed java please restart your computer. Somehow the system environment variables has not been updated.

**Comment by Quibus-burst** [comment] 2018-04-01 19:08
This is now fixed in V2.0.2

**Closed by Quibus-burst** 2018-04-01 19:08 UTC
